sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dhagash2310/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dhagash2310/react-test npm test

after_success:
  - docker build -t dhagash2310/multi-client ./client
  - docker build -t dhagash2310/multi-nginx ./nginx
  - docker build -t dhagash2310/multi-server ./server
  - docker build -t dhagash2310/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dhagash2310/multi-client
  - docker push dhagash2310/multi-nginx
  - docker push dhagash2310/multi-server
  - docker push dhagash2310/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-301543735738
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

